model:
  name: "microsoft/phi-2"
  quantization: "4bit"
  
dataset:
  name: "medmcqa"
  max_samples: 5000
  augmentation: true
  
training:
  num_epochs: 3
  batch_size: 4
  learning_rate: 1e-4
  warmup_ratio: 0.1
  
lora:
  r: 64
  lora_alpha: 128
  lora_dropout: 0.1
  target_modules: ["q_proj", "v_proj", "k_proj", "o_proj"]
